/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/components/AboutModal.vue')['default']
    BackButton: typeof import('./src/components/actions/BackButton.vue')['default']
    CategoryBadge: typeof import('./src/components/CategoryBadge.vue')['default']
    CountryLabel: typeof import('./src/components/CountryLabel.vue')['default']
    FilterPanel: typeof import('./src/components/FilterPanel.vue')['default']
    FloatingMeta: typeof import('./src/components/FloatingMeta.vue')['default']
    IBiArrowLeft: typeof import('~icons/bi/arrow-left')['default']
    IBiArrowRepeat: typeof import('~icons/bi/arrow-repeat')['default']
    IBiBoxArrowUpRight: typeof import('~icons/bi/box-arrow-up-right')['default']
    IBiCalendar3: typeof import('~icons/bi/calendar3')['default']
    IBiCheck2Circle: typeof import('~icons/bi/check2-circle')['default']
    IBiChevronRight: typeof import('~icons/bi/chevron-right')['default']
    IBiEmojiDizzy: typeof import('~icons/bi/emoji-dizzy')['default']
    IBiGeoAlt: typeof import('~icons/bi/geo-alt')['default']
    IBiGlobe2: typeof import('~icons/bi/globe2')['default']
    IBiImage: typeof import('~icons/bi/image')['default']
    IBiMap: typeof import('~icons/bi/map')['default']
    IBiPinMapFill: typeof import('~icons/bi/pin-map-fill')['default']
    IBiSearch: typeof import('~icons/bi/search')['default']
    IBiShareFill: typeof import('~icons/bi/share-fill')['default']
    IBiTag: typeof import('~icons/bi/tag')['default']
    IBiX: typeof import('~icons/bi/x')['default']
    IBiZoomIn: typeof import('~icons/bi/zoom-in')['default']
    LocationMap: typeof import('./src/components/map/LocationMap.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    MoreMenu: typeof import('./src/components/MoreMenu.vue')['default']
    NavigateButton: typeof import('./src/components/actions/NavigateButton.vue')['default']
    ProjectDetails: typeof import('./src/components/project/ProjectDetails.vue')['default']
    ProjectGallery: typeof import('./src/components/project/ProjectGallery.vue')['default']
    ProjectGalleryModal: typeof import('./src/components/project/ProjectGalleryModal.vue')['default']
    ProjectListItem: typeof import('./src/components/project/ProjectListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchModal: typeof import('./src/components/SearchModal.vue')['default']
    ShareButton: typeof import('./src/components/actions/ShareButton.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    StateBadge: typeof import('./src/components/StateBadge.vue')['default']
  }
}
