/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/actions/BackButton.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdownItem']
    BImg: typeof import('bootstrap-vue-next/components/BImg')['BImg']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BOverlay: typeof import('bootstrap-vue-next/components/BOverlay')['BOverlay']
    CategoryBadge: typeof import('./src/components/CategoryBadge.vue')['default']
    CountryLabel: typeof import('./src/components/CountryLabel.vue')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    IBiPinMapFill: typeof import('~icons/bi/pin-map-fill')['default']
    LocationMap: typeof import('./src/components/map/LocationMap.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    NavigateButton: typeof import('./src/components/actions/NavigateButton.vue')['default']
    ProjectDetails: typeof import('./src/components/project/ProjectDetails.vue')['default']
    ProjectGallery: typeof import('./src/components/project/ProjectGallery.vue')['default']
    ProjectGalleryModal: typeof import('./src/components/project/ProjectGalleryModal.vue')['default']
    ProjectListItem: typeof import('./src/components/project/ProjectListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./src/components/actions/ShareButton.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
  }
}
