/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./src/components/actions/BackButton.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardGroup: typeof import('bootstrap-vue-next')['BCardGroup']
    BCardImg: typeof import('bootstrap-vue-next')['BCardImg']
    BCarousel: typeof import('bootstrap-vue-next')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BPlaceholder: typeof import('bootstrap-vue-next')['BPlaceholder']
    BPlaceholderCard: typeof import('bootstrap-vue-next')['BPlaceholderCard']
    BPlaceholderWrapper: typeof import('bootstrap-vue-next')['BPlaceholderWrapper']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    CategoryBadge: typeof import('./src/components/CategoryBadge.vue')['default']
    CountryLabel: typeof import('./src/components/CountryLabel.vue')['default']
    IBiFilter: typeof import('~icons/bi/filter')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    IBiPinMapFill: typeof import('~icons/bi/pin-map-fill')['default']
    IBiShareFill: typeof import('~icons/bi/share-fill')['default']
    LocationMap: typeof import('./src/components/map/LocationMap.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    NavigateButton: typeof import('./src/components/actions/NavigateButton.vue')['default']
    ProjectDetails: typeof import('./src/components/project/ProjectDetails.vue')['default']
    ProjectGallery: typeof import('./src/components/project/ProjectGallery.vue')['default']
    ProjectGalleryModal: typeof import('./src/components/project/ProjectGalleryModal.vue')['default']
    ProjectListItem: typeof import('./src/components/project/ProjectListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./src/components/actions/ShareButton.vue')['default']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next')['vBToggle']
  }
}
