[build]
  publish = "dist"
  command = "npm run build && npm run budget"

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  audits = ["performance"]
  output_path = "lighthouse"
  fail_deploy_on_score_thresholds = false

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
