[build]
  publish = "dist"
  command = "npm run build:prod"

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
  audits = ["performance"]
  output_path = "lighthouse"
  fail_deploy_on_score_thresholds = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"